CREATE TABLE IF NOT EXISTS cards (
    CardsID BIGINT NOT NULL,
    CardsStatus TEXT NOT NULL,
    CardsAUTHOR TEXT NOT NULL,
    CardsNAME TEXT NOT NULL,
    CardsURL TEXT NOT NULL,
    CardsDesc TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS my_cards (
    UserID BIGINT NOT NULL,
    CardsID BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    UserID BIGINT NOT NULL,
    Username TEXT NOT NULL,
    last_card_time DATETIME,
    coins BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS market (
    ListingID INTEGER PRIMARY KEY AUTOINCREMENT,
    SellerID BIGINT NOT NULL,
    SellerUsername TEXT NOT NULL,
    CardsID BIGINT NOT NULL,
    Price BIGINT NOT NULL,
    ListedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS promos (
    PromoID INTEGER PRIMARY KEY AUTOINCREMENT,
    PromoCode TEXT NOT NULL,
    UsesLeft INTEGER NOT NULL,
    RewardType TEXT NOT NULL,
    RewardAmount INTEGER NOT NULL,
    ExpiryDate DATETIME
);
CREATE TABLE IF NOT EXISTS promo_uses (
    UserID BIGINT NOT NULL,
    PromoID INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS album_list (
    AlbumID INTEGER PRIMARY KEY AUTOINCREMENT,
    AlbumName TEXT NOT NULL,
    AlbumAuthor TEXT NOT NULL,
    RequiredCards TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS my_album (
    UserID BIGINT NOT NULL,
    AlbumID INTEGER NOT NULL,
    CompletedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AlbumID) REFERENCES album_list(AlbumID)
);
CREATE TABLE IF NOT EXISTS job_list (
    JobID INTEGER PRIMARY KEY,
    JobNAME TEXT NOT NULL,
    JobPRICE INTEGER NOT NULL,
    JobDESC TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS my_job (
    UserID BIGINT NOT NULL,
    Username TEXT,
    job_id INTEGER,
    last_work DATETIME,
    xp INTEGER NOT NULL DEFAULT 0,
    lvl INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (job_id) REFERENCES job_list(JobID)
);